import {
  TransactionStatus,
  RiskLevel,
  PaymentMethod,
  PaymentStepStatus,
  type OfferTransaction,
} from "@/types/offer-transaction";

export const mockTransactions: OfferTransaction[] = [
  {
    offerId: "OFR-100001",
    status: TransactionStatus.Completed,
    amount: 1250.99,
    currency: "USD",
    paymentMethod: PaymentMethod.CreditCard,
    vendor: {
      id: "vendor-stripe-101",
      name: "Stripe",
      code: "STRIPE",
      riskScore: 12,
      successRate: 98.5,
    },
    risk: {
      level: RiskLevel.Low,
      score: 15,
      factors: ["velocity_check", "address_verification"],
      reviewRequired: false,
      assessedAt: "2026-03-09T10:00:00Z",
    },
    paymentSteps: [
      {
        id: "step-1-1001",
        name: "Authorization",
        status: PaymentStepStatus.Completed,
        processor: "Stripe",
        startedAt: "2026-03-09T10:00:00Z",
        completedAt: "2026-03-09T10:00:02Z",
        duration: 2000,
        details: {},
      },
      {
        id: "step-2-1002",
        name: "Fraud Check",
        status: PaymentStepStatus.Completed,
        processor: "Stripe",
        startedAt: "2026-03-09T10:00:02Z",
        completedAt: "2026-03-09T10:00:03Z",
        duration: 1000,
        details: {},
      },
      {
        id: "step-3-1003",
        name: "Capture",
        status: PaymentStepStatus.Completed,
        processor: "Stripe",
        startedAt: "2026-03-09T10:00:03Z",
        completedAt: "2026-03-09T10:00:05Z",
        duration: 2000,
        details: {},
      },
      {
        id: "step-4-1004",
        name: "Settlement",
        status: PaymentStepStatus.Completed,
        processor: "Stripe",
        startedAt: "2026-03-09T10:00:05Z",
        completedAt: "2026-03-09T10:00:08Z",
        duration: 3000,
        details: {},
      },
    ],
    payloads: [
      {
        id: "payload-10001",
        timestamp: "2026-03-09T10:00:00Z",
        direction: "request",
        endpoint: "/api/v1/payments/authorize",
        method: "POST",
        statusCode: null,
        headers: { "Content-Type": "application/json" },
        body: { amount: 1250.99, currency: "USD", method: "credit_card" },
      },
      {
        id: "payload-10002",
        timestamp: "2026-03-09T10:00:02Z",
        direction: "response",
        endpoint: "/api/v1/payments/authorize",
        method: "POST",
        statusCode: 200,
        headers: { "Content-Type": "application/json" },
        body: { status: "authorized", transactionId: "txn-500001" },
      },
    ],
    createdAt: "2026-03-09T10:00:00Z",
    updatedAt: "2026-03-09T10:00:08Z",
  },
  {
    offerId: "OFR-100002",
    status: TransactionStatus.Failed,
    amount: 5430.0,
    currency: "EUR",
    paymentMethod: PaymentMethod.BankTransfer,
    vendor: {
      id: "vendor-adyen-202",
      name: "Adyen",
      code: "ADYEN",
      riskScore: 45,
      successRate: 96.2,
    },
    risk: {
      level: RiskLevel.High,
      score: 72,
      factors: ["geo_mismatch", "amount_threshold", "new_customer"],
      reviewRequired: true,
      assessedAt: "2026-03-09T08:30:00Z",
    },
    paymentSteps: [
      {
        id: "step-1-2001",
        name: "Authorization",
        status: PaymentStepStatus.Completed,
        processor: "Adyen",
        startedAt: "2026-03-09T08:30:00Z",
        completedAt: "2026-03-09T08:30:03Z",
        duration: 3000,
        details: {},
      },
      {
        id: "step-2-2002",
        name: "Fraud Check",
        status: PaymentStepStatus.Failed,
        processor: "Adyen",
        startedAt: "2026-03-09T08:30:03Z",
        completedAt: "2026-03-09T08:30:05Z",
        duration: 2000,
        details: { reason: "risk_score_exceeded" },
      },
      {
        id: "step-3-2003",
        name: "Capture",
        status: PaymentStepStatus.Skipped,
        processor: "Adyen",
        startedAt: "2026-03-09T08:30:05Z",
        completedAt: null,
        duration: null,
        details: {},
      },
      {
        id: "step-4-2004",
        name: "Settlement",
        status: PaymentStepStatus.Skipped,
        processor: "Adyen",
        startedAt: "2026-03-09T08:30:05Z",
        completedAt: null,
        duration: null,
        details: {},
      },
    ],
    payloads: [
      {
        id: "payload-20001",
        timestamp: "2026-03-09T08:30:00Z",
        direction: "request",
        endpoint: "/api/v1/payments/authorize",
        method: "POST",
        statusCode: null,
        headers: { "Content-Type": "application/json" },
        body: { amount: 5430.0, currency: "EUR", method: "bank_transfer" },
      },
      {
        id: "payload-20002",
        timestamp: "2026-03-09T08:30:05Z",
        direction: "response",
        endpoint: "/api/v1/payments/authorize",
        method: "POST",
        statusCode: 400,
        headers: { "Content-Type": "application/json" },
        body: { status: "declined", reason: "fraud_check_failed" },
      },
    ],
    createdAt: "2026-03-09T08:30:00Z",
    updatedAt: "2026-03-09T08:30:05Z",
  },
  {
    offerId: "OFR-100003",
    status: TransactionStatus.Processing,
    amount: 89.5,
    currency: "GBP",
    paymentMethod: PaymentMethod.DigitalWallet,
    vendor: {
      id: "vendor-braintree-303",
      name: "Braintree",
      code: "BRAINTREE",
      riskScore: 8,
      successRate: 99.1,
    },
    risk: {
      level: RiskLevel.Low,
      score: 5,
      factors: ["device_fingerprint"],
      reviewRequired: false,
      assessedAt: "2026-03-09T11:15:00Z",
    },
    paymentSteps: [
      {
        id: "step-1-3001",
        name: "Authorization",
        status: PaymentStepStatus.Completed,
        processor: "Braintree",
        startedAt: "2026-03-09T11:15:00Z",
        completedAt: "2026-03-09T11:15:01Z",
        duration: 1000,
        details: {},
      },
      {
        id: "step-2-3002",
        name: "Fraud Check",
        status: PaymentStepStatus.Completed,
        processor: "Braintree",
        startedAt: "2026-03-09T11:15:01Z",
        completedAt: "2026-03-09T11:15:02Z",
        duration: 800,
        details: {},
      },
      {
        id: "step-3-3003",
        name: "Capture",
        status: PaymentStepStatus.InProgress,
        processor: "Braintree",
        startedAt: "2026-03-09T11:15:02Z",
        completedAt: null,
        duration: null,
        details: {},
      },
      {
        id: "step-4-3004",
        name: "Settlement",
        status: PaymentStepStatus.Pending,
        processor: "Braintree",
        startedAt: "2026-03-09T11:15:02Z",
        completedAt: null,
        duration: null,
        details: {},
      },
    ],
    payloads: [
      {
        id: "payload-30001",
        timestamp: "2026-03-09T11:15:00Z",
        direction: "request",
        endpoint: "/api/v1/payments/authorize",
        method: "POST",
        statusCode: null,
        headers: { "Content-Type": "application/json" },
        body: { amount: 89.5, currency: "GBP", method: "digital_wallet" },
      },
      {
        id: "payload-30002",
        timestamp: "2026-03-09T11:15:01Z",
        direction: "response",
        endpoint: "/api/v1/payments/authorize",
        method: "POST",
        statusCode: 201,
        headers: { "Content-Type": "application/json" },
        body: { status: "authorized", transactionId: "txn-500003" },
      },
    ],
    createdAt: "2026-03-09T11:15:00Z",
    updatedAt: "2026-03-09T11:15:02Z",
  },
  {
    offerId: "OFR-100004",
    status: TransactionStatus.Completed,
    amount: 320.0,
    currency: "CAD",
    paymentMethod: PaymentMethod.DebitCard,
    vendor: {
      id: "vendor-worldpay-404",
      name: "Worldpay",
      code: "WORLDPAY",
      riskScore: 22,
      successRate: 97.8,
    },
    risk: {
      level: RiskLevel.Medium,
      score: 35,
      factors: ["bin_check", "3ds_result"],
      reviewRequired: false,
      assessedAt: "2026-03-08T16:45:00Z",
    },
    paymentSteps: [
      {
        id: "step-1-4001",
        name: "Authorization",
        status: PaymentStepStatus.Completed,
        processor: "Worldpay",
        startedAt: "2026-03-08T16:45:00Z",
        completedAt: "2026-03-08T16:45:04Z",
        duration: 4000,
        details: {},
      },
      {
        id: "step-2-4002",
        name: "Fraud Check",
        status: PaymentStepStatus.Completed,
        processor: "Worldpay",
        startedAt: "2026-03-08T16:45:04Z",
        completedAt: "2026-03-08T16:45:06Z",
        duration: 2000,
        details: {},
      },
      {
        id: "step-3-4003",
        name: "Capture",
        status: PaymentStepStatus.Completed,
        processor: "Worldpay",
        startedAt: "2026-03-08T16:45:06Z",
        completedAt: "2026-03-08T16:45:09Z",
        duration: 3000,
        details: {},
      },
      {
        id: "step-4-4004",
        name: "Settlement",
        status: PaymentStepStatus.Completed,
        processor: "Worldpay",
        startedAt: "2026-03-08T16:45:09Z",
        completedAt: "2026-03-08T16:45:12Z",
        duration: 3000,
        details: {},
      },
    ],
    payloads: [
      {
        id: "payload-40001",
        timestamp: "2026-03-08T16:45:00Z",
        direction: "request",
        endpoint: "/api/v1/payments/authorize",
        method: "POST",
        statusCode: null,
        headers: { "Content-Type": "application/json" },
        body: { amount: 320.0, currency: "CAD", method: "debit_card" },
      },
      {
        id: "payload-40002",
        timestamp: "2026-03-08T16:45:04Z",
        direction: "response",
        endpoint: "/api/v1/payments/authorize",
        method: "POST",
        statusCode: 200,
        headers: { "Content-Type": "application/json" },
        body: { status: "authorized", transactionId: "txn-500004" },
      },
    ],
    createdAt: "2026-03-08T16:45:00Z",
    updatedAt: "2026-03-08T16:45:12Z",
  },
  {
    offerId: "OFR-100005",
    status: TransactionStatus.Pending,
    amount: 15750.0,
    currency: "USD",
    paymentMethod: PaymentMethod.PayLater,
    vendor: {
      id: "vendor-checkout-505",
      name: "Checkout.com",
      code: "CHECKOUT",
      riskScore: 58,
      successRate: 95.3,
    },
    risk: {
      level: RiskLevel.Critical,
      score: 88,
      factors: ["amount_threshold", "new_customer", "geo_mismatch", "fraud_model_v2"],
      reviewRequired: true,
      assessedAt: "2026-03-09T12:00:00Z",
    },
    paymentSteps: [
      {
        id: "step-1-5001",
        name: "Authorization",
        status: PaymentStepStatus.Pending,
        processor: "Checkout.com",
        startedAt: "2026-03-09T12:00:00Z",
        completedAt: null,
        duration: null,
        details: {},
      },
      {
        id: "step-2-5002",
        name: "Fraud Check",
        status: PaymentStepStatus.Pending,
        processor: "Checkout.com",
        startedAt: "2026-03-09T12:00:00Z",
        completedAt: null,
        duration: null,
        details: {},
      },
      {
        id: "step-3-5003",
        name: "Capture",
        status: PaymentStepStatus.Pending,
        processor: "Checkout.com",
        startedAt: "2026-03-09T12:00:00Z",
        completedAt: null,
        duration: null,
        details: {},
      },
      {
        id: "step-4-5004",
        name: "Settlement",
        status: PaymentStepStatus.Pending,
        processor: "Checkout.com",
        startedAt: "2026-03-09T12:00:00Z",
        completedAt: null,
        duration: null,
        details: {},
      },
    ],
    payloads: [
      {
        id: "payload-50001",
        timestamp: "2026-03-09T12:00:00Z",
        direction: "request",
        endpoint: "/api/v1/payments/authorize",
        method: "POST",
        statusCode: null,
        headers: { "Content-Type": "application/json" },
        body: { amount: 15750.0, currency: "USD", method: "pay_later" },
      },
    ],
    createdAt: "2026-03-09T12:00:00Z",
    updatedAt: "2026-03-09T12:00:00Z",
  },
];
