import {
  TransactionStatus,
  RiskLevel,
  PaymentMethod,
  PaymentStepStatus,
  type OfferTransaction,
} from "@/types/offer-transaction";

export const mockTransactions: OfferTransaction[] = [
  {
    offerId: "OFR-100001",
    customerName: "Sarah Chen",
    status: TransactionStatus.Completed,
    amount: 1250.99,
    currency: "USD",
    paymentMethod: PaymentMethod.CreditCard,
    tokenVendor: "VGS",
    pspName: "Stripe",
    pspSuccess: true,
    vendor: {
      id: "vendor-stripe-101",
      name: "Stripe",
      code: "STRIPE",
      riskScore: 12,
      successRate: 98.5,
    },
    risk: {
      level: RiskLevel.Low,
      score: 15,
      factors: ["velocity_check", "address_verification"],
      reviewRequired: false,
      assessedAt: "2026-03-09T10:00:00Z",
    },
    riskVendors: [
      {
        vendorName: "LexisNexis",
        vendorCode: "LN",
        decision: "approve",
        riskScore: 12,
        latencyMs: 180,
        phase: "pre_auth",
        rulesTriggered: ["velocity_check_pass", "identity_verified"],
        matchDetails: { identityConfidence: 0.95, velocityScore: 2 },
      },
      {
        vendorName: "Forter",
        vendorCode: "FORTER",
        decision: "approve",
        riskScore: 18,
        latencyMs: 220,
        phase: "pre_auth",
        rulesTriggered: ["device_trust_high", "behavioral_normal"],
        matchDetails: { deviceTrust: 0.92, behaviorScore: 88 },
      },
      {
        vendorName: "Accertify",
        vendorCode: "ACCERTIFY",
        decision: "approve",
        riskScore: 15,
        latencyMs: 150,
        phase: "pre_auth",
        rulesTriggered: ["geo_match", "card_on_file"],
        matchDetails: { geoMatch: true, cardAge: "2y" },
      },
      {
        vendorName: "Forter",
        vendorCode: "FORTER",
        decision: "approve",
        riskScore: 10,
        latencyMs: 95,
        phase: "post_auth",
        rulesTriggered: ["post_auth_clear"],
        matchDetails: { postAuthRisk: "low" },
      },
      {
        vendorName: "Accertify",
        vendorCode: "ACCERTIFY",
        decision: "approve",
        riskScore: 8,
        latencyMs: 110,
        phase: "post_auth",
        rulesTriggered: ["settlement_verified"],
        matchDetails: { settlementStatus: "clean" },
      },
    ],
    paymentSteps: [
      {
        id: "step-1-1001",
        name: "LexisNexis Check",
        status: PaymentStepStatus.Completed,
        processor: "LexisNexis",
        startedAt: "2026-03-09T10:00:00Z",
        completedAt: "2026-03-09T10:00:00.180Z",
        duration: 180,
        details: { decision: "approve", score: 12 },
      },
      {
        id: "step-2-1001",
        name: "Forter Pre-Auth",
        status: PaymentStepStatus.Completed,
        processor: "Forter",
        startedAt: "2026-03-09T10:00:00.180Z",
        completedAt: "2026-03-09T10:00:00.400Z",
        duration: 220,
        details: { decision: "approve", score: 18 },
      },
      {
        id: "step-3-1001",
        name: "Accertify Pre-Auth",
        status: PaymentStepStatus.Completed,
        processor: "Accertify",
        startedAt: "2026-03-09T10:00:00.400Z",
        completedAt: "2026-03-09T10:00:00.550Z",
        duration: 150,
        details: { decision: "approve", score: 15 },
      },
      {
        id: "step-4-1001",
        name: "Payment Authorization",
        status: PaymentStepStatus.Completed,
        processor: "Stripe",
        startedAt: "2026-03-09T10:00:00.550Z",
        completedAt: "2026-03-09T10:00:02Z",
        duration: 1450,
        details: { authCode: "A12345", responseCode: "00" },
      },
      {
        id: "step-5-1001",
        name: "Forter Post-Auth",
        status: PaymentStepStatus.Completed,
        processor: "Forter",
        startedAt: "2026-03-09T10:00:02Z",
        completedAt: "2026-03-09T10:00:02.095Z",
        duration: 95,
        details: { decision: "approve" },
      },
      {
        id: "step-6-1001",
        name: "Accertify Post-Auth",
        status: PaymentStepStatus.Completed,
        processor: "Accertify",
        startedAt: "2026-03-09T10:00:02.095Z",
        completedAt: "2026-03-09T10:00:02.205Z",
        duration: 110,
        details: { decision: "approve" },
      },
    ],
    lifecycleSteps: [
      { name: "Authorization", status: PaymentStepStatus.Completed, amount: 1250.99, responseCode: "00", message: "Approved", timestamp: "2026-03-09T10:00:02Z", isPartial: false },
      { name: "Capture", status: PaymentStepStatus.Completed, amount: 1250.99, responseCode: "00", message: "Captured successfully", timestamp: "2026-03-09T10:05:00Z", isPartial: false },
      { name: "Refund", status: PaymentStepStatus.Skipped, amount: null, responseCode: null, message: null, timestamp: null, isPartial: false },
      { name: "Credit", status: PaymentStepStatus.Skipped, amount: null, responseCode: null, message: null, timestamp: null, isPartial: false },
    ],
    payloads: [
      { id: "payload-10001", timestamp: "2026-03-09T10:00:00Z", direction: "request", endpoint: "/api/v1/lexisnexis/check", method: "POST", statusCode: null, headers: { "Content-Type": "application/json" }, body: { customerId: "cust-001", amount: 1250.99, currency: "USD" }, vendor: "LexisNexis", phase: "pre_auth" },
      { id: "payload-10002", timestamp: "2026-03-09T10:00:00.180Z", direction: "response", endpoint: "/api/v1/lexisnexis/check", method: "POST", statusCode: 200, headers: { "Content-Type": "application/json" }, body: { decision: "approve", score: 12, confidence: 0.95 }, vendor: "LexisNexis", phase: "pre_auth" },
      { id: "payload-10003", timestamp: "2026-03-09T10:00:00.180Z", direction: "request", endpoint: "/api/v1/forter/evaluate", method: "POST", statusCode: null, headers: { "Content-Type": "application/json" }, body: { orderId: "OFR-100001", amount: 1250.99, deviceId: "dev-abc" }, vendor: "Forter", phase: "pre_auth" },
      { id: "payload-10004", timestamp: "2026-03-09T10:00:00.400Z", direction: "response", endpoint: "/api/v1/forter/evaluate", method: "POST", statusCode: 200, headers: { "Content-Type": "application/json" }, body: { decision: "approve", riskScore: 18, deviceTrust: 0.92 }, vendor: "Forter", phase: "pre_auth" },
      { id: "payload-10005", timestamp: "2026-03-09T10:00:00.550Z", direction: "request", endpoint: "/api/v1/stripe/authorize", method: "POST", statusCode: null, headers: { "Content-Type": "application/json", Authorization: "Bearer sk_***" }, body: { amount: 125099, currency: "usd", source: "tok_visa", capture: false }, vendor: "Stripe", phase: "payment" },
      { id: "payload-10006", timestamp: "2026-03-09T10:00:02Z", direction: "response", endpoint: "/api/v1/stripe/authorize", method: "POST", statusCode: 200, headers: { "Content-Type": "application/json" }, body: { id: "ch_1abc", status: "authorized", authCode: "A12345" }, vendor: "Stripe", phase: "payment" },
    ],
    createdAt: "2026-03-09T10:00:00Z",
    updatedAt: "2026-03-09T10:05:00Z",
  },
  {
    offerId: "OFR-100002",
    customerName: "Marcus Johnson",
    status: TransactionStatus.Failed,
    amount: 5430.0,
    currency: "EUR",
    paymentMethod: PaymentMethod.BankTransfer,
    tokenVendor: "Basis Theory",
    pspName: "Adyen",
    pspSuccess: false,
    vendor: {
      id: "vendor-adyen-202",
      name: "Adyen",
      code: "ADYEN",
      riskScore: 45,
      successRate: 96.2,
    },
    risk: {
      level: RiskLevel.High,
      score: 72,
      factors: ["geo_mismatch", "amount_threshold", "new_customer"],
      reviewRequired: true,
      assessedAt: "2026-03-09T08:30:00Z",
    },
    riskVendors: [
      { vendorName: "LexisNexis", vendorCode: "LN", decision: "review", riskScore: 65, latencyMs: 210, phase: "pre_auth", rulesTriggered: ["geo_mismatch", "new_identity"], matchDetails: { identityConfidence: 0.45, geoRisk: "high" } },
      { vendorName: "Forter", vendorCode: "FORTER", decision: "decline", riskScore: 82, latencyMs: 340, phase: "pre_auth", rulesTriggered: ["amount_threshold", "device_unknown", "behavioral_anomaly"], matchDetails: { deviceTrust: 0.2, behaviorScore: 25, amountAnomaly: true } },
      { vendorName: "Accertify", vendorCode: "ACCERTIFY", decision: "decline", riskScore: 78, latencyMs: 190, phase: "pre_auth", rulesTriggered: ["velocity_exceeded", "card_not_on_file", "new_customer"], matchDetails: { velocityCount: 12, cardAge: "new", customerAge: "1d" } },
    ],
    paymentSteps: [
      { id: "step-1-2001", name: "LexisNexis Check", status: PaymentStepStatus.Completed, processor: "LexisNexis", startedAt: "2026-03-09T08:30:00Z", completedAt: "2026-03-09T08:30:00.210Z", duration: 210, details: { decision: "review", score: 65 } },
      { id: "step-2-2001", name: "Forter Pre-Auth", status: PaymentStepStatus.Failed, processor: "Forter", startedAt: "2026-03-09T08:30:00.210Z", completedAt: "2026-03-09T08:30:00.550Z", duration: 340, details: { decision: "decline", score: 82 } },
      { id: "step-3-2001", name: "Accertify Pre-Auth", status: PaymentStepStatus.Failed, processor: "Accertify", startedAt: "2026-03-09T08:30:00.550Z", completedAt: "2026-03-09T08:30:00.740Z", duration: 190, details: { decision: "decline", score: 78 } },
      { id: "step-4-2001", name: "Payment Authorization", status: PaymentStepStatus.Skipped, processor: "Adyen", startedAt: "2026-03-09T08:30:00.740Z", completedAt: null, duration: null, details: { reason: "risk_declined" } },
    ],
    lifecycleSteps: [
      { name: "Authorization", status: PaymentStepStatus.Failed, amount: 5430.0, responseCode: "05", message: "Declined by risk engine", timestamp: "2026-03-09T08:30:00.740Z", isPartial: false },
      { name: "Capture", status: PaymentStepStatus.Skipped, amount: null, responseCode: null, message: null, timestamp: null, isPartial: false },
      { name: "Refund", status: PaymentStepStatus.Skipped, amount: null, responseCode: null, message: null, timestamp: null, isPartial: false },
      { name: "Credit", status: PaymentStepStatus.Skipped, amount: null, responseCode: null, message: null, timestamp: null, isPartial: false },
    ],
    payloads: [
      { id: "payload-20001", timestamp: "2026-03-09T08:30:00Z", direction: "request", endpoint: "/api/v1/lexisnexis/check", method: "POST", statusCode: null, headers: { "Content-Type": "application/json" }, body: { customerId: "cust-002", amount: 5430.0, currency: "EUR" }, vendor: "LexisNexis", phase: "pre_auth" },
      { id: "payload-20002", timestamp: "2026-03-09T08:30:00.210Z", direction: "response", endpoint: "/api/v1/lexisnexis/check", method: "POST", statusCode: 200, headers: { "Content-Type": "application/json" }, body: { decision: "review", score: 65, flags: ["geo_mismatch"] }, vendor: "LexisNexis", phase: "pre_auth" },
      { id: "payload-20003", timestamp: "2026-03-09T08:30:00.210Z", direction: "request", endpoint: "/api/v1/forter/evaluate", method: "POST", statusCode: null, headers: { "Content-Type": "application/json" }, body: { orderId: "OFR-100002", amount: 5430.0, deviceId: "dev-unknown" }, vendor: "Forter", phase: "pre_auth" },
      { id: "payload-20004", timestamp: "2026-03-09T08:30:00.550Z", direction: "response", endpoint: "/api/v1/forter/evaluate", method: "POST", statusCode: 200, headers: { "Content-Type": "application/json" }, body: { decision: "decline", riskScore: 82, reason: "behavioral_anomaly" }, vendor: "Forter", phase: "pre_auth" },
      { id: "payload-20005", timestamp: "2026-03-09T08:30:00.550Z", direction: "request", endpoint: "/api/v1/accertify/assess", method: "POST", statusCode: null, headers: { "Content-Type": "application/json" }, body: { orderId: "OFR-100002", amount: 5430.0 }, vendor: "Accertify", phase: "pre_auth" },
      { id: "payload-20006", timestamp: "2026-03-09T08:30:00.740Z", direction: "response", endpoint: "/api/v1/accertify/assess", method: "POST", statusCode: 200, headers: { "Content-Type": "application/json" }, body: { decision: "decline", riskScore: 78, velocityExceeded: true }, vendor: "Accertify", phase: "pre_auth" },
    ],
    createdAt: "2026-03-09T08:30:00Z",
    updatedAt: "2026-03-09T08:30:00.740Z",
  },
  {
    offerId: "OFR-100003",
    customerName: "Emily Rodriguez",
    status: TransactionStatus.Processing,
    amount: 89.5,
    currency: "GBP",
    paymentMethod: PaymentMethod.DigitalWallet,
    tokenVendor: "VGS",
    pspName: "Braintree",
    pspSuccess: true,
    vendor: { id: "vendor-braintree-303", name: "Braintree", code: "BRAINTREE", riskScore: 8, successRate: 99.1 },
    risk: { level: RiskLevel.Low, score: 5, factors: ["device_fingerprint"], reviewRequired: false, assessedAt: "2026-03-09T11:15:00Z" },
    riskVendors: [
      { vendorName: "LexisNexis", vendorCode: "LN", decision: "approve", riskScore: 5, latencyMs: 120, phase: "pre_auth", rulesTriggered: ["known_device", "repeat_customer"], matchDetails: { identityConfidence: 0.99 } },
      { vendorName: "Forter", vendorCode: "FORTER", decision: "approve", riskScore: 8, latencyMs: 145, phase: "pre_auth", rulesTriggered: ["trusted_device", "low_amount"], matchDetails: { deviceTrust: 0.98 } },
      { vendorName: "Accertify", vendorCode: "ACCERTIFY", decision: "approve", riskScore: 6, latencyMs: 100, phase: "pre_auth", rulesTriggered: ["trusted_customer"], matchDetails: { customerRisk: "low" } },
    ],
    paymentSteps: [
      { id: "step-1-3001", name: "LexisNexis Check", status: PaymentStepStatus.Completed, processor: "LexisNexis", startedAt: "2026-03-09T11:15:00Z", completedAt: "2026-03-09T11:15:00.120Z", duration: 120, details: { decision: "approve" } },
      { id: "step-2-3001", name: "Forter Pre-Auth", status: PaymentStepStatus.Completed, processor: "Forter", startedAt: "2026-03-09T11:15:00.120Z", completedAt: "2026-03-09T11:15:00.265Z", duration: 145, details: { decision: "approve" } },
      { id: "step-3-3001", name: "Accertify Pre-Auth", status: PaymentStepStatus.Completed, processor: "Accertify", startedAt: "2026-03-09T11:15:00.265Z", completedAt: "2026-03-09T11:15:00.365Z", duration: 100, details: { decision: "approve" } },
      { id: "step-4-3001", name: "Payment Authorization", status: PaymentStepStatus.Completed, processor: "Braintree", startedAt: "2026-03-09T11:15:00.365Z", completedAt: "2026-03-09T11:15:01Z", duration: 635, details: { authCode: "B67890" } },
      { id: "step-5-3001", name: "Forter Post-Auth", status: PaymentStepStatus.InProgress, processor: "Forter", startedAt: "2026-03-09T11:15:01Z", completedAt: null, duration: null, details: {} },
    ],
    lifecycleSteps: [
      { name: "Authorization", status: PaymentStepStatus.Completed, amount: 89.5, responseCode: "00", message: "Approved", timestamp: "2026-03-09T11:15:01Z", isPartial: false },
      { name: "Capture", status: PaymentStepStatus.InProgress, amount: 89.5, responseCode: null, message: "Capture pending", timestamp: null, isPartial: false },
      { name: "Refund", status: PaymentStepStatus.Pending, amount: null, responseCode: null, message: null, timestamp: null, isPartial: false },
      { name: "Credit", status: PaymentStepStatus.Pending, amount: null, responseCode: null, message: null, timestamp: null, isPartial: false },
    ],
    payloads: [
      { id: "payload-30001", timestamp: "2026-03-09T11:15:00Z", direction: "request", endpoint: "/api/v1/lexisnexis/check", method: "POST", statusCode: null, headers: { "Content-Type": "application/json" }, body: { customerId: "cust-003", amount: 89.5 }, vendor: "LexisNexis", phase: "pre_auth" },
      { id: "payload-30002", timestamp: "2026-03-09T11:15:00.120Z", direction: "response", endpoint: "/api/v1/lexisnexis/check", method: "POST", statusCode: 200, headers: { "Content-Type": "application/json" }, body: { decision: "approve", score: 5 }, vendor: "LexisNexis", phase: "pre_auth" },
      { id: "payload-30003", timestamp: "2026-03-09T11:15:00.365Z", direction: "request", endpoint: "/api/v1/braintree/authorize", method: "POST", statusCode: null, headers: { "Content-Type": "application/json" }, body: { amount: 89.5, currency: "GBP", nonce: "wallet-nonce-xyz" }, vendor: "Braintree", phase: "payment" },
      { id: "payload-30004", timestamp: "2026-03-09T11:15:01Z", direction: "response", endpoint: "/api/v1/braintree/authorize", method: "POST", statusCode: 201, headers: { "Content-Type": "application/json" }, body: { status: "authorized", transactionId: "txn-500003" }, vendor: "Braintree", phase: "payment" },
    ],
    createdAt: "2026-03-09T11:15:00Z",
    updatedAt: "2026-03-09T11:15:01Z",
  },
  {
    offerId: "OFR-100004",
    customerName: "David Park",
    status: TransactionStatus.Refunded,
    amount: 320.0,
    currency: "CAD",
    paymentMethod: PaymentMethod.DebitCard,
    tokenVendor: "Basis Theory",
    pspName: "Worldpay",
    pspSuccess: true,
    vendor: { id: "vendor-worldpay-404", name: "Worldpay", code: "WORLDPAY", riskScore: 22, successRate: 97.8 },
    risk: { level: RiskLevel.Medium, score: 35, factors: ["bin_check", "3ds_result"], reviewRequired: false, assessedAt: "2026-03-08T16:45:00Z" },
    riskVendors: [
      { vendorName: "LexisNexis", vendorCode: "LN", decision: "approve", riskScore: 30, latencyMs: 200, phase: "pre_auth", rulesTriggered: ["bin_check_pass"], matchDetails: { binCountry: "CA" } },
      { vendorName: "Forter", vendorCode: "FORTER", decision: "approve", riskScore: 35, latencyMs: 280, phase: "pre_auth", rulesTriggered: ["3ds_passed", "moderate_amount"], matchDetails: { threeDsResult: "Y" } },
      { vendorName: "Accertify", vendorCode: "ACCERTIFY", decision: "approve", riskScore: 32, latencyMs: 160, phase: "pre_auth", rulesTriggered: ["3ds_authenticated"], matchDetails: { authResult: "full_auth" } },
      { vendorName: "Forter", vendorCode: "FORTER", decision: "approve", riskScore: 20, latencyMs: 90, phase: "post_auth", rulesTriggered: ["post_auth_clear"], matchDetails: {} },
      { vendorName: "Accertify", vendorCode: "ACCERTIFY", decision: "approve", riskScore: 18, latencyMs: 85, phase: "post_auth", rulesTriggered: ["settlement_ok"], matchDetails: {} },
    ],
    paymentSteps: [
      { id: "step-1-4001", name: "LexisNexis Check", status: PaymentStepStatus.Completed, processor: "LexisNexis", startedAt: "2026-03-08T16:45:00Z", completedAt: "2026-03-08T16:45:00.200Z", duration: 200, details: {} },
      { id: "step-2-4001", name: "Forter Pre-Auth", status: PaymentStepStatus.Completed, processor: "Forter", startedAt: "2026-03-08T16:45:00.200Z", completedAt: "2026-03-08T16:45:00.480Z", duration: 280, details: {} },
      { id: "step-3-4001", name: "Accertify Pre-Auth", status: PaymentStepStatus.Completed, processor: "Accertify", startedAt: "2026-03-08T16:45:00.480Z", completedAt: "2026-03-08T16:45:00.640Z", duration: 160, details: {} },
      { id: "step-4-4001", name: "Payment Authorization", status: PaymentStepStatus.Completed, processor: "Worldpay", startedAt: "2026-03-08T16:45:00.640Z", completedAt: "2026-03-08T16:45:04Z", duration: 3360, details: { authCode: "W99887" } },
      { id: "step-5-4001", name: "Forter Post-Auth", status: PaymentStepStatus.Completed, processor: "Forter", startedAt: "2026-03-08T16:45:04Z", completedAt: "2026-03-08T16:45:04.090Z", duration: 90, details: {} },
      { id: "step-6-4001", name: "Accertify Post-Auth", status: PaymentStepStatus.Completed, processor: "Accertify", startedAt: "2026-03-08T16:45:04.090Z", completedAt: "2026-03-08T16:45:04.175Z", duration: 85, details: {} },
    ],
    lifecycleSteps: [
      { name: "Authorization", status: PaymentStepStatus.Completed, amount: 320.0, responseCode: "00", message: "Approved", timestamp: "2026-03-08T16:45:04Z", isPartial: false },
      { name: "Capture", status: PaymentStepStatus.Completed, amount: 320.0, responseCode: "00", message: "Captured", timestamp: "2026-03-08T16:50:00Z", isPartial: false },
      { name: "Refund", status: PaymentStepStatus.Completed, amount: 200.0, responseCode: "00", message: "Partial refund processed", timestamp: "2026-03-09T09:00:00Z", isPartial: true },
      { name: "Credit", status: PaymentStepStatus.Skipped, amount: null, responseCode: null, message: null, timestamp: null, isPartial: false },
    ],
    payloads: [
      { id: "payload-40001", timestamp: "2026-03-08T16:45:00Z", direction: "request", endpoint: "/api/v1/worldpay/authorize", method: "POST", statusCode: null, headers: { "Content-Type": "application/json" }, body: { amount: 320.0, currency: "CAD" }, vendor: "Worldpay", phase: "payment" },
      { id: "payload-40002", timestamp: "2026-03-08T16:45:04Z", direction: "response", endpoint: "/api/v1/worldpay/authorize", method: "POST", statusCode: 200, headers: { "Content-Type": "application/json" }, body: { status: "authorized", transactionId: "txn-500004" }, vendor: "Worldpay", phase: "payment" },
      { id: "payload-40003", timestamp: "2026-03-09T09:00:00Z", direction: "request", endpoint: "/api/v1/worldpay/refund", method: "POST", statusCode: null, headers: { "Content-Type": "application/json" }, body: { transactionId: "txn-500004", amount: 200.0, reason: "customer_request" }, vendor: "Worldpay", phase: "payment" },
      { id: "payload-40004", timestamp: "2026-03-09T09:00:02Z", direction: "response", endpoint: "/api/v1/worldpay/refund", method: "POST", statusCode: 200, headers: { "Content-Type": "application/json" }, body: { status: "refunded", amount: 200.0, refundId: "ref-001" }, vendor: "Worldpay", phase: "payment" },
    ],
    createdAt: "2026-03-08T16:45:00Z",
    updatedAt: "2026-03-09T09:00:02Z",
  },
  {
    offerId: "OFR-100005",
    customerName: "Aisha Patel",
    status: TransactionStatus.Pending,
    amount: 15750.0,
    currency: "USD",
    paymentMethod: PaymentMethod.PayLater,
    tokenVendor: "VGS",
    pspName: "Checkout.com",
    pspSuccess: false,
    vendor: { id: "vendor-checkout-505", name: "Checkout.com", code: "CHECKOUT", riskScore: 58, successRate: 95.3 },
    risk: { level: RiskLevel.Critical, score: 88, factors: ["amount_threshold", "new_customer", "geo_mismatch", "fraud_model_v2"], reviewRequired: true, assessedAt: "2026-03-09T12:00:00Z" },
    riskVendors: [
      { vendorName: "LexisNexis", vendorCode: "LN", decision: "review", riskScore: 75, latencyMs: 250, phase: "pre_auth", rulesTriggered: ["high_amount", "identity_mismatch", "geo_anomaly"], matchDetails: { identityConfidence: 0.35, amountPercentile: 99 } },
      { vendorName: "Forter", vendorCode: "FORTER", decision: "decline", riskScore: 92, latencyMs: 380, phase: "pre_auth", rulesTriggered: ["fraud_model_v2_trigger", "new_device", "high_amount", "velocity_spike"], matchDetails: { deviceTrust: 0.1, fraudModelScore: 0.95 } },
      { vendorName: "Accertify", vendorCode: "ACCERTIFY", decision: "decline", riskScore: 88, latencyMs: 210, phase: "pre_auth", rulesTriggered: ["amount_exceeds_limit", "new_customer_high_value", "no_3ds"], matchDetails: { amountLimit: 5000, customerAge: "2h" } },
    ],
    paymentSteps: [
      { id: "step-1-5001", name: "LexisNexis Check", status: PaymentStepStatus.Completed, processor: "LexisNexis", startedAt: "2026-03-09T12:00:00Z", completedAt: "2026-03-09T12:00:00.250Z", duration: 250, details: { decision: "review" } },
      { id: "step-2-5001", name: "Forter Pre-Auth", status: PaymentStepStatus.Failed, processor: "Forter", startedAt: "2026-03-09T12:00:00.250Z", completedAt: "2026-03-09T12:00:00.630Z", duration: 380, details: { decision: "decline" } },
      { id: "step-3-5001", name: "Accertify Pre-Auth", status: PaymentStepStatus.Failed, processor: "Accertify", startedAt: "2026-03-09T12:00:00.630Z", completedAt: "2026-03-09T12:00:00.840Z", duration: 210, details: { decision: "decline" } },
      { id: "step-4-5001", name: "Payment Authorization", status: PaymentStepStatus.Pending, processor: "Checkout.com", startedAt: "2026-03-09T12:00:00.840Z", completedAt: null, duration: null, details: { status: "awaiting_manual_review" } },
    ],
    lifecycleSteps: [
      { name: "Authorization", status: PaymentStepStatus.Pending, amount: 15750.0, responseCode: null, message: "Awaiting manual review", timestamp: null, isPartial: false },
      { name: "Capture", status: PaymentStepStatus.Pending, amount: null, responseCode: null, message: null, timestamp: null, isPartial: false },
      { name: "Refund", status: PaymentStepStatus.Pending, amount: null, responseCode: null, message: null, timestamp: null, isPartial: false },
      { name: "Credit", status: PaymentStepStatus.Pending, amount: null, responseCode: null, message: null, timestamp: null, isPartial: false },
    ],
    payloads: [
      { id: "payload-50001", timestamp: "2026-03-09T12:00:00Z", direction: "request", endpoint: "/api/v1/lexisnexis/check", method: "POST", statusCode: null, headers: { "Content-Type": "application/json" }, body: { customerId: "cust-005", amount: 15750.0, currency: "USD" }, vendor: "LexisNexis", phase: "pre_auth" },
      { id: "payload-50002", timestamp: "2026-03-09T12:00:00.250Z", direction: "response", endpoint: "/api/v1/lexisnexis/check", method: "POST", statusCode: 200, headers: { "Content-Type": "application/json" }, body: { decision: "review", score: 75, flags: ["high_amount"] }, vendor: "LexisNexis", phase: "pre_auth" },
      { id: "payload-50003", timestamp: "2026-03-09T12:00:00.250Z", direction: "request", endpoint: "/api/v1/forter/evaluate", method: "POST", statusCode: null, headers: { "Content-Type": "application/json" }, body: { orderId: "OFR-100005", amount: 15750.0 }, vendor: "Forter", phase: "pre_auth" },
      { id: "payload-50004", timestamp: "2026-03-09T12:00:00.630Z", direction: "response", endpoint: "/api/v1/forter/evaluate", method: "POST", statusCode: 200, headers: { "Content-Type": "application/json" }, body: { decision: "decline", riskScore: 92, fraudModel: "v2" }, vendor: "Forter", phase: "pre_auth" },
    ],
    createdAt: "2026-03-09T12:00:00Z",
    updatedAt: "2026-03-09T12:00:00.840Z",
  },
];
